GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Imphc29uIiwiaWQiOiI2MzQ1Mzk4MDVhMzdjMjlmNmRhNGNkZmYiLCJpYXQiOjE2NjU1ODg2NDh9.SzJZD31iln1L-PdEUECdnB8l1qCLLLgdsC5wPQjESBs

{
"title": "sunny",
"author":"kim dam min",
"url":"kathmandu.post",
"likes":3,
"userId":"6343c3317db8faddba15d804"
}

###
DELETE http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/users
Content-type: application/json

{
"username": "jason",
"name":"jason",
"password":"grass"

}

###
POST http://localhost:3003/api/login
Content-type: application/json

{
"username": "jason",
"password":"grass"

}